modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license="${mod_license}"

[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    version = "${mod_version}" #mandatory
    displayName = "${mod_name}"#mandatory
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/seasonhud"
    logoFile= "SeasonHud.png"
    logoBlur = true
    authors= "${mod_authors}" #optional
    description = "${mod_description}"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId = "forge" #mandatory
    mandatory = true #mandatory
    versionRange = "${forge_version_range}" #mandatory
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange="${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "sereneseasons"
    mandatory = true
    versionRange = "[1.20-9.0.0.41,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "xaerominimap"
    mandatory = false
    versionRange = "[23.5.0,)"
    ordering = "AFTER"
    side = "CLIENT"